### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by LukeHankey** [Vthechamp22/kindly-kappa#11]
Remove samples folder and update the readme. Change the license to include all collaborators names.

Can probably keep the entire readme as a reference but add on top of it all of the details of our project.

- [x] Remove samples directory
- [x] Update readme
- [x] Update license

**Comment by kappq** [comment]
I think we can wait until the jam ends before writing the documentation and updating the README, we should have 4 extra days for that.

**Comment by LukeHankey** [comment]
> I think we can wait until the jam ends before writing the documentation and updating the README, we should have 4 extra days for that.

Yup.

**Comment by kappq** [comment]
> * [ ]  Update license

I think the MIT license is required, so we can't really update it.

**Comment by LukeHankey** [comment]
> > * [ ]   Update license
> 
> I think the MIT license is required, so we can't really update it.

In terms of adding our names and changing the year of the project start

**Comment by LukeHankey** [comment]
We done!
