### ISSUE TITLE
Server rooms - Fixes

### ISSUE THREAD

**Issue by LukeHankey** [Vthechamp22/kindly-kappa#22]
`async def room(websocket: WebSocket, room_name: str) -> None:`

The function name clashes with parameter names of all of the manager methods. - Deepsource

Upon receiving a client connection, create a check to see if they have joined a pre-existing room by checking `manager._rooms`. 
```py
def new_user_in_existing_room(...):
    ...

if new_user_in_existing_room():
    await manager.broadcast(data, room_name)
else:
   await manager.broadcast(data, room_name, everyone=True)
```

The manager.broadcast documentation should include the `everyone` parameter.

**Comment by LukeHankey** [comment]
Just thinking now, will the else statement in the `manager.broadcast()` method ever be reached?

1 player:
- We receive the data from the client
- We then broadcast the modified code back to the client (`everyone=True`)

Multiplayer:
- Receive data from all clients
- Broadcast all the changes to each client in real-time (`everyone=True`) again.

Looking back at #16, the code will be reached upon a new user joining an existing room so we do need to check the number of clients in a room. I just have named the function confusingly.

**Comment by kappq** [comment]
There is also a problem with the `broadcast` function and the `everyone` parameter: currently, if `everyone` is set to `False` the message won't be sent to the owner of the room, however, the owner is not necessarily the one who sent the message.

So for example:
- Client A creates a room called `hello` (now Client A is the owner of `hello`)
- Clent B connects to `hello`
- Client A sends a message, but, because he is the owner of the room, he won't receive it
- Client B receives the message
- Client B sends a message, and he receives it, but Client A doesn't because he is the owner

**Comment by LukeHankey** [comment]
> There is also a problem with the `broadcast` function and the `everyone` parameter: currently, if `everyone` is set to `False` the message won't be sent to the owner of the room, however, the owner is not necessarily the one who sent the message.
> 
> So for example:
> 
> * Client A creates a room called `hello` (now Client A is the owner of `hello`)
> * Clent B connects to `hello`
> * Client A sends a message, but, because he is the owner of the room, he won't receive it
> * Client B receives the message
> * Client B sends a message, and he receives it, but Client A doesn't because he is the owner

That makes sense. We could create a cache of the most recent code that was sent and broadcast that to any new user that joins an existing room, before any new data is received but after the connection has been made.

Everyone would only be set to false from the example in the first post which shouldn't affect Client A sending a message.

Using your example with my thoughts:
- Client A creates a room called `hello` (now Client A is the owner of `hello`)
- Client B connects to `hello`
- Client B will trigger a broadcast event with `everyone=False` and receive the same data that is visible on Client A's editor
- Client A sends a message, `everyone=True`, both Client A and B receive it.
- Client B sends a message, and both receive it.

**Comment by kappq** [comment]
I think a simpler solution would be just passing the client to the `broadcast` function instead of `everyone`, so the `ConnectionManager` knows who sent the message.

**Comment by LukeHankey** [comment]
> I think a simpler solution would be just passing the client to the `broadcast` function instead of `everyone`, so the `ConnectionManager` knows who sent the message.

Ok, what would the logic look like here?

**Comment by kappq** [comment]
> Ok, what would the logic look like here?

Something like this:
```py
async def broadcast(self, data, room, sender: Client):
    for connection self._rooms[room]["clients"]:
        if connection == sender:
            continue
        await connection.send(data)
```

**Comment by LukeHankey** [comment]
> > Ok, what would the logic look like here?
> 
> Something like this:
> 
> ```python
> async def broadcast(self, data, room, sender: Client):
>     for connection self._rooms[room]["clients"]:
>         if connection == sender:
>             continue
>         await connection.send(data)
> ```

I guess that makes sense since the sender will already have the updated code. This should apply for any number of clients connected to a room making changes, right?

One more thing is will the client instances be comparable? Or should there be a `__eq__()` implemented onto the Client class, which compares the `id`, or would it be better to just compare the id here `if connection.id == sender.id:`?

**Comment by kappq** [comment]
> I guess that makes sense since the sender will already have the updated code. This should apply for any number of clients connected to a room making changes, right?

Yes, the sender should already have the updated code and the function should work for any number of clients making changes. 

> One more thing is will the client instances be comparable? Or should there be a `__eq__()` implemented onto the Client class, which compares the `id`, or would it be better to just compare the id here `if connection.id == sender.id:`?

Oh, I didn't think about it, an `__eq__` method would be pretty neat.
