### ISSUE TITLE
Create Data Models

### ISSUE THREAD

**Issue by LukeHankey** [Vthechamp22/kindly-kappa#31]
Create data models using pydantics BaseModel class for all of the event types found in #25 (Examples)

Since the `type` key is required in every request, we could make a `BaseModel` called `Event` that has a field `type` and a field `data`. The field `type` should be an `Enum` variant, while the `data` should be an instance of something like `ConnectionData`, we can then create different classes to represent the data of different types of events.

Something like this:
```py
class EventType(Enum):
    ...

class EventData(BaseModel):
    pass

class ConnectionData(EventData):
    difficulty: int
    room_code: str

class InsertData(EventData):
    ...

class Event:
    type: EventType
    message: str
    data: EventData
```

_Originally posted by @kappq in https://github.com/Vthechamp22/kindly-kappa/pull/28#discussion_r928313606_

**Comment by kappq** [comment]
We might as well define the event specification here.

**Comment by LukeHankey** [comment]
```py
class EventType(Enum):
    ...

class EventData(BaseModel):
    pass

class ConnectionData(BaseModel):
    difficulty: int
    room_code: str

class InsertData(BaseModel):
    ...

class Event(BaseModel):
    type: EventType
    message: str
    data: EventData
```

All models should inherit from pydantic's BaseModel class and then the attributes should be of the different classes
