### ISSUE TITLE
Code Storage Implementation Issue

### ISSUE THREAD

**Issue by bensgilbert** [Vthechamp22/kindly-kappa#34]
Currently, in the frontend and backend we store our code as an array of lines. This allows us to modify and return random lines to present a challenge to the user.

However a problem arises, when editing text in the frontend editor, the user can select a span of text and delete it like so:
![image](https://user-images.githubusercontent.com/68397475/180670522-7569ed8e-f36e-4f6f-a128-e77f29477368.png)

If the user deletes it then with our current implementation, a `remove` event would be sent, but with what data? Since the deletion occurs across 2 lines and starts and ends at unpredictable index's on the line we will have a hard time processing it with our current line based cache.

**Proposal**
If we store the code as a string rather then an array of lines then we can easily insert/replace/remove by index and allows the frontend to send the modifications to the backend in a more comprehensible way.

Insert:
You would insert the specified text at the specified index by splitting the existing string and inserting the text in the middle
Replace:
Given a start and end index and the new text, you can easily splice the code to replace a certain bit
Remove:
The same as replace except it's replacing with an empty string

Example (selected text starts at index 7 and ends at index 35 (this includes the newline character):
![image](https://user-images.githubusercontent.com/68397475/180670836-b1f269b5-4aef-4326-8b75-ec1ba4e79517.png)
insert `" beautiful"` at index 12 to output "hello beautiful world"
replace index 7 to 35 with "new text" will replace the text to make a single print statement
remove index 7 to 18 with "" to output an empty string rather then "hello world" and "example"

In fact, the insert event can also be implemented with replace, its just replacing a 0 width string with the new string at a certain index.

This issue aims to solve the problems that occur when trying to send this data from the frontend to the backend.
**The backend doesn't need to change much at all to adapt**, sure they have to store the code as a string but they dont need to change any of their modification code since they can just use the strings `splitlines()` method to get it back into the desired format.

**Comment by bensgilbert** [comment]
An added benefit to this is we can replace all our code modification messages with the `replace` event to reduce complexity. And with this implementation, we can better represent selected text to other users when there's multiple users since we only have to send the start and end index.

**Comment by LukeHankey** [comment]
So the front end will convert all of the clients text into a string, including adding newlines? Will removing a portion of text that breaks out onto multiple lines also correctly remove the newlines?
```py
def say_hello() -> str:
    return "Hello!"

print(say_hello())

```
So the above will turn into this: `"def say_hello() -> str:\n    return "Hello!"\n\nprint(say_hello())\n"`
And if I were to delete the printing part:
```py
def say_hello() -> str:
    return "Hello!"

```
Are you able to correctly string together: `"def say_hello() -> str:\n"` and send an event that `"    return "Hello!"\n\nprint(say_hello())\n"` was removed?

**Comment by bensgilbert** [comment]
> the above will turn into this: "def say_hello() -> str:\n return "Hello!"\n\nprint(say_hello())\n"

Yes

> Are you able to correctly string together: "def say_hello() -> str:\n" and send an event that " return "Hello!"\n\nprint(say_hello())\n" was removed?

I won’t need to manually mess around with the new lines, if you wanted to remove the print bit then you’d replace everything after index 44 (give or take, it’s hard to count manually lol) with an empty string, effectively removing it.

**Comment by LukeHankey** [comment]
> I won’t need to manually mess around with the new lines, if you wanted to remove the print bit then you’d replace everything after index 44 (give or take, it’s hard to count manually lol) with an empty string, effectively removing it.

So the client would send to the server some response like:
```json
{
    "type": "replace",
    "data": {
        "message": "replaces code",
        "code": [
            {
                "from": 24,
                "to": 61,
                "value": ""
            }
        ]
    }
}
```

**Comment by bensgilbert** [comment]
Yes, that would represent a remove in that example. But you could also represent inserts and normal replaces with just this system.

**Comment by LukeHankey** [comment]
I like the idea. What do you think about the above structure change? Is the `from`, `to`, and `value` clear?

**Comment by bensgilbert** [comment]
Yes, I think that model is ready for production 😁 I’ll start implementing it tomorrow (or today as it’s current past 1am).

**Comment by LukeHankey** [comment]
This new structure has been adopted into the codebase.
