### ISSUE TITLE
Dev tools

### ISSUE THREAD

**Issue by LukeHankey** [Vthechamp22/kindly-kappa#43]
Here are some other useful flake8 plugins which could be useful to our project:

- https://github.com/best-doctor/flake8-class-attributes-order
- https://github.com/nhoad/flake8-unused-arguments
- https://github.com/best-doctor/flake8-variables-names

Static Type Checking:
- Mypy
- Pyright

Please take a look at them and comment.

**Comment by kappq** [comment]
All the `flake8` plugins you suggested seem really useful. As the type checker, I would go with `mypy` (that's what I've always used).

My only concern is that they might be too strict and slow down the development a bit.

**Comment by LukeHankey** [comment]
They should all be really helpful with keeping our code maintained and well checked. We don't have to add them to pre-commit either to enforce them, just remember to do them manually every now and then if we don't want the strictness
