### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by kappq** [Vthechamp22/kindly-kappa#45]
Currently, the project structure is not ideal, for instance, we have all the Python files in the `server` directory and the logic for the `Client` and the `ConnectionManager` in `main.py`.

A more complex project structure may not be required, but that would be a good improvement.

Any changes can be discussed below.

**Comment by LukeHankey** [comment]
Are you thinking about separating the client from main.py?

**Comment by kappq** [comment]
> Are you thinking about separating the client from main.py?

Yes, the `ConnectionManager` as well. I've done just that in #46 .

**Comment by LukeHankey** [comment]
Perhaps rename the connection_manager file to just `manager` as it manages more than just the connection.
