### ISSUE TITLE
Code Modifiers

### ISSUE THREAD

**Issue by LukeHankey** [Vthechamp22/kindly-kappa#5]
To add some functions that take in the code snapshot and return part of the code modified.

Some examples:
- Add random SyntaxErrors:
  - Removing `:` from the end of a function signature, loops or if statements
  - Changing the name of keywords (def -> definition)
  - Adding in empty blocks ```if something:``` (nothing afterwards)
- Comment some code out
- Change function names when called to something else:
```py
def add_one(a: int) -> int:
    return a + 1

add_one(5) # -> bug(5)
```

I think these would be alright for now and can introduce more complex bugs if we have the time to create levels of difficulty. Will start working on a PR for this.

**Comment by Montarex23** [comment]
A few ideas:
<ul>
  <li><b>Boolean swap</b> - change True to False and False to True</li>
  <li><b>Condition destroyer</b> - replace == with = in if conditions</li>
  <li><b>Type chaos</b> - mix keywords like int, str, bool</li>
    <i>For example change str(len("abc")) to bool(len("abc"))</i>
  <li><b>Bracket hell</b> - add or remove some brackets</li>
</ul>

**Comment by LukeHankey** [comment]
> A few ideas:
> 
> * Boolean swap - change True to False and False to True
> * Condition destroyer - replace == with = in if conditions
> * Type chaos - mix keywords like int, str, bool
> For example change str(len("abc")) to bool(len("abc"))
> * Bracket hell - add or remove some brackets

Haha, I like the names. Do you want to give this a go?

**Comment by Montarex23** [comment]
Yeah, I can. After I finish them should I make a pull request to code-modifiers branch or what?

**Comment by LukeHankey** [comment]
> Yeah, I can. After I finish them should I make a pull request to code-modifiers branch or what?

Just create your branch based off of code-modifiers or main (depending on when you do it). 
`git checkout code-modifiers` -> This gets the latest changes from that branch then you want to do:
`git checkout -b branchName` and start working on this branch.

If the code-modifiers branch is merged into main before you get started, then do the same steps but replace `code-modifiers` with `main`
