### ISSUE TITLE
Code Timer

### ISSUE THREAD

**Issue by kappq** [Vthechamp22/kindly-kappa#53]
We need a timer that monitors the time it takes the user to solve the challenge.

We mainly have two options:
- Implement it in the front end, but there is a risk that the user will mess with it.
- Implement it in the back end, the timer would run as a background task.

Any changes can be discussed below.

**Comment by LukeHankey** [comment]
Perhaps implement on the front end but also have the background task on the backend. We can check periodically that the timers match up and sync them if not. Maybe through the connection and sync events as I don't think they will be out of sync very often and these events don't fire too much.

**Comment by kappq** [comment]
> Perhaps implement on the front end but also have the background task on the backend. We can check periodically that the timers match up and sync them if not. Maybe through the connection and sync events as I don't think they will be out of sync very often and these events don't fire too much.

Why though? Wouldn't one timer be enough?

**Comment by LukeHankey** [comment]
> > Perhaps implement on the front end but also have the background task on the backend. We can check periodically that the timers match up and sync them if not. Maybe through the connection and sync events as I don't think they will be out of sync very often and these events don't fire too much.
> 
> Why though? Wouldn't one timer be enough?

It would, yeah. Thought it would be nice to display to the frontend though.

**Comment by kappq** [comment]
> > > Perhaps implement on the front end but also have the background task on the backend. We can check periodically that the timers match up and sync them if not. Maybe through the connection and sync events as I don't think they will be out of sync very often and these events don't fire too much.
> > 
> > 
> > Why though? Wouldn't one timer be enough?
> 
> It would, yeah. Thought it would be nice to display to the frontend though.

Oh right, I didn't think about that. Also because having an event just for the timer might be too much.

**Comment by LukeHankey** [comment]
Exactly, the server and client will be talking a lot with sending possibly hundreds of requests per min
