### ISSUE TITLE
ConnectionManager too bloated

### ISSUE THREAD

**Issue by LukeHankey** [Vthechamp22/kindly-kappa#54]
That is currently the `ConnectionManager` class: it stores the code and can update and modify it (for the modifications it depends on the `Modifier` class obviously).

My idea would be having something like an `Editor` class that does all of this:
```py
class Editor:
    def __init__(...):
        self.code = ...
        ...
    def update_code_cache(...):
        ...
    def modify_code(...):
        ...
```

_Originally posted by @kappq in https://github.com/Vthechamp22/kindly-kappa/pull/35#discussion_r932702321_

Separating any and all of the code/cache logic from the connection manager makes much more sense than keeping them together.

**Comment by kappq** [comment]
I was thinking about creating a `Room` class instead.

What brought me to this thought was the difficulty of the room: it seems like the `ConnectionManager` isn't supposed to hold the information, but at the same time, the editor shouldn't as well.

So here comes the `Room` class: it would hold all the information related to a room (e.g. owner ID, clients, etc. Basically what `ActiveRoom` currently has) plus the code and the methods to manipulate it.

Let me know what you think about this.

**Comment by LukeHankey** [comment]
> I was thinking about creating a `Room` class instead.
> 
> What brought me to this thought was the difficulty of the room: it seems like the `ConnectionManager` isn't supposed to hold the information, but at the same time, the editor shouldn't as well.
> 
> So here comes the `Room` class: it would hold all the information related to a room (e.g. owner ID, clients, etc. Basically what `ActiveRoom` currently has) plus the code and the methods to manipulate it.
> 
> Let me know what you think about this.

Yes, I guess from your original example, the Editor here would be deemed as a subclass of the Room. This looks better.
